# Generated by Django 3.2.1 on 2022-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=50)),
                ('number', models.CharField(blank=True, default='', max_length=15)),
                ('collegeName', models.CharField(blank=True, default='', max_length=100)),
                ('events_registered', models.CharField(blank=True, default='', max_length=100)),
                ('datestamp', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
            ],
        ),
    ]
